(part "ATWINC1500-MR210PA"
    (packageRef "ATWINC1500MR210PA")
    (interface
        (port "1" (symbPinId 1) (portName "GPIO_18") (portType INOUT))
        (port "2" (symbPinId 2) (portName "I2C_SCL") (portType INOUT))
        (port "3" (symbPinId 3) (portName "I2C_SDA") (portType INOUT))
        (port "4" (symbPinId 4) (portName "RESET_N") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "NC_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "NC_3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "NC_4") (portType INOUT))
        (port "9" (symbPinId 9) (portName "GND_1") (portType INOUT))
        (port "10" (symbPinId 10) (portName "SPI_CFG") (portType INOUT))
        (port "11" (symbPinId 11) (portName "WAKE") (portType INOUT))
        (port "12" (symbPinId 12) (portName "GND_2") (portType INOUT))
        (port "13" (symbPinId 13) (portName "IRQN") (portType INOUT))
        (port "14" (symbPinId 14) (portName "UART_TXD") (portType INOUT))
        (port "15" (symbPinId 15) (portName "SPI_RXD") (portType INOUT))
        (port "16" (symbPinId 16) (portName "SPI_SSN") (portType INOUT))
        (port "17" (symbPinId 17) (portName "SPI_TXD") (portType INOUT))
        (port "18" (symbPinId 18) (portName "SPI_SCK") (portType INOUT))
        (port "19" (symbPinId 19) (portName "UART_RXD") (portType INOUT))
        (port "20" (symbPinId 20) (portName "VBATT") (portType INOUT))
        (port "21" (symbPinId 21) (portName "GPIO_1") (portType INOUT))
        (port "22" (symbPinId 22) (portName "CHIP_EN") (portType INOUT))
        (port "23" (symbPinId 23) (portName "VDDIO") (portType INOUT))
        (port "24" (symbPinId 24) (portName "1P3V_TP") (portType INOUT))
        (port "25" (symbPinId 25) (portName "NC_5") (portType INOUT))
        (port "26" (symbPinId 26) (portName "GPIO_15") (portType INOUT))
        (port "27" (symbPinId 27) (portName "GPIO_16") (portType INOUT))
        (port "28" (symbPinId 28) (portName "GND_3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Microchip")
    (property "Manufacturer_Part_Number" "ATWINC1500-MR210PA")
    (property "Mouser_Part_Number" "556-WINC1500-MR210PA")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Microchip-Technology-Atmel/ATWINC1500-MR210PA?qs=C0FNv%2F5jaI9at6Iw6IE9ag%3D%3D")
    (property "Arrow_Part_Number" "ATWINC1500-MR210PA")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/atwinc1500-mr210pa/microchip-technology?region=nac")
    (property "Description" "Module 802.11b/g/n 2.484GHz 72000Kbps 28-Pin SMD Module")
    (property "Datasheet_Link" "http://ww1.microchip.com/downloads/en/DeviceDoc/atmel-42376-smartconnect-winc1500-mr210pa_datasheet.pdf")
    (property "symbolName1" "ATWINC1500-MR210PA")
)
